'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA=path.resolve(process.env.DATA_DIR||path.join(ROOT,'data')),CONFIG=JSON.parse(fs.readFileSync(path.join(ROOT,'config.json'),'utf8'));fs.mkdirSync(DATA,{recursive:true});
const PORT=Number(process.env.PORT)||10000,SCORE_FILE=path.join(DATA,'scores.jsonl'),scores=[],seenRuns=new Set(),clients=new Map(),duelQueue=[],rooms=new Map(),roomClients=new Map();let revision=1;
try{if(fs.existsSync(SCORE_FILE))for(const line of fs.readFileSync(SCORE_FILE,'utf8').split(/\r?\n/)){if(!line.trim())continue;try{const r=JSON.parse(line);scores.push(r);if(r.runId)seenRuns.add(r.runId)}catch{}}}catch{}
const now=()=>Date.now(),id=p=>p+'_'+crypto.randomBytes(8).toString('hex');
function cleanName(v){return String(v||'PLAYER').replace(/<[^>]*>/g,'').replace(/[^a-zA-Z0-9 ._\-'’]/g,'').replace(/\s+/g,' ').trim().slice(0,20)||'PLAYER'}
function cleanId(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100)}
function allowedOrigin(req){const o=req.headers.origin||'';if(!o)return '*';const env=process.env.PUBLIC_SITE_URL;if(env&&o===env)return o;return CONFIG.allowedOrigins.includes(o)?o:'null'}
function json(res,status,obj,origin='*'){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(obj))}
function sse(c,p){if(c.closed)return;try{c.res.write(`data: ${JSON.stringify(p)}\n\n`)}catch{c.closed=true}}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>350000){reject(Error('Too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Error('Bad JSON'))}})})}
function leaderboard(){const map=new Map();for(const r of scores){const k=r.playerId||r.name.toLowerCase(),p=map.get(k);if(!p||r.score>p.score)map.set(k,r)}return [...map.values()].sort((a,b)=>b.score-a.score||new Date(a.createdAt)-new Date(b.createdAt)).slice(0,100)}
function recentScores(){return scores.slice(-12).reverse().map(r=>({name:r.name,score:r.score,createdAt:r.createdAt}))}
function rewriteScores(){fs.writeFileSync(SCORE_FILE,scores.map(r=>JSON.stringify(r)).join('\n')+(scores.length?'\n':''))}
function saveScore(r){scores.push(r);seenRuns.add(r.runId);while(scores.length>CONFIG.maxScores)scores.shift();fs.appendFileSync(SCORE_FILE,JSON.stringify(r)+'\n')}
function bestForPlayer(pid){return scores.filter(r=>r.playerId===pid).sort((a,b)=>b.score-a.score||new Date(a.createdAt)-new Date(b.createdAt))[0]||null}
function hostAuthorized(b){return String(b?.hostCode||'')===String(process.env.HOST_CODE||'host4536')}
function queueJoin(pid,name){let q=duelQueue.find(x=>x.playerId===pid);if(q){q.name=name;q.lastSeen=now();return q}q={id:id('duel'),playerId:pid,name,joinedAt:now(),lastSeen:now()};duelQueue.push(q);return q}
function makeCode(){let c;do{c=String(Math.floor(100000+Math.random()*900000))}while([...rooms.values()].some(r=>r.joinCode===c&&r.status!=='ended'));return c}
function publicPlayers(r){return r.players.map(p=>({playerId:p.playerId,name:p.name,seat:p.seat,role:p.role,ready:true}))}
function summary(r){return{id:r.id,joinCode:r.joinCode,game:'shooting-gallery',mode:r.mode,status:r.status,hostPlayerId:r.hostPlayerId,hostName:r.hostName,targetPlayers:r.targetPlayers,players:publicPlayers(r),playerNames:r.players.map(p=>p.name),playerCount:r.players.length,currentPlayerId:r.currentPlayerId,currentPlayerName:r.currentPlayerName,currentSeat:r.currentSeat,secondsRemaining:r.secondsRemaining,createdAt:r.createdAt,startedAt:r.startedAt,lastEventAt:r.lastEventAt,watchers:roomClients.get(r.id)?.size||0,canStart:r.status==='lobby'&&r.players.length===r.targetPlayers}}
function roomBy(b){const rid=cleanId(b.roomId);if(rid&&rooms.has(rid))return rooms.get(rid);const code=String(b.joinCode||'').replace(/\D/g,'').slice(0,6);return [...rooms.values()].find(r=>r.joinCode===code&&r.status!=='ended')||null}
function createRoom(b,mode='online'){const pid=cleanId(b.hostPlayerId),name=cleanName(b.hostName),target=Math.max(2,Math.min(4,Number(b.targetPlayers)||2));if(!pid)throw Error('hostPlayerId required');const r={id:id('room'),joinCode:makeCode(),mode,status:'lobby',hostToken:id('host'),hostPlayerId:pid,hostName:name,targetPlayers:target,players:[{playerId:pid,name,seat:1,role:'host',token:id('player')}],currentPlayerId:'',currentPlayerName:'',currentSeat:0,secondsRemaining:60,createdAt:now(),startedAt:0,lastEventAt:now(),eventSeq:0,recentEvents:[]};rooms.set(r.id,r);return r}
function authPlayer(r,b){if(!r)return null;if(String(b.hostToken||'')===r.hostToken)return r.players.find(p=>p.playerId===r.hostPlayerId);const pid=cleanId(b.playerId),tok=String(b.playerToken||'');return r.players.find(p=>p.playerId===pid&&p.token===tok)||null}
function broadcastRoom(r,payload){r.lastEventAt=now();const ev={...payload,roomId:r.id,seq:++r.eventSeq,serverAt:now()};r.recentEvents.push(ev);if(r.recentEvents.length>120)r.recentEvents.shift();const set=roomClients.get(r.id);if(set)for(const c of set.values())sse(c,{type:'game-event',event:ev})}
function prune(){const t=now(),liveT=Math.max(120000,Number(CONFIG.liveGameTtlSeconds||900)*1000),lobbyT=Math.max(120000,Number(CONFIG.multiplayerLobbyTtlSeconds||600)*1000);for(let i=duelQueue.length-1;i>=0;i--)if(t-duelQueue[i].lastSeen>CONFIG.duelWaitTtlSeconds*1000)duelQueue.splice(i,1);for(const [k,c] of clients)if(c.closed||t-c.lastSeen>CONFIG.presenceTtlSeconds*1000){try{c.res.end()}catch{}clients.delete(k)}for(const [rid,r] of rooms){const ttl=r.status==='lobby'?lobbyT:liveT;if(r.status!=='ended'&&t-r.lastEventAt>ttl){r.status='ended';broadcastRoom(r,{type:'room-ended',reason:'expired'})}if(r.status==='ended'&&t-r.lastEventAt>ttl*2){rooms.delete(rid);roomClients.delete(rid)}}}
function state(){prune();return{build:CONFIG.build,revision,online:clients.size,leaderboard:leaderboard().slice(0,10),recent:recentScores(),duel:{waiting:duelQueue.length,names:duelQueue.slice(0,5).map(x=>x.name)},liveGames:[...rooms.values()].filter(r=>r.status==='live').sort((a,b)=>b.startedAt-a.startedAt).map(summary),openGames:[...rooms.values()].filter(r=>r.status==='lobby').sort((a,b)=>b.createdAt-a.createdAt).map(summary)}}
function broadcast(){revision++;const st=state();for(const c of clients.values())sse(c,{type:'state',state:st})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'),origin=allowedOrigin(req);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});return res.end()}
 if(url.pathname==='/health')return json(res,200,{ok:true,service:'Medley Arcade Website Live Authority',build:CONFIG.build,state:state()},origin);
 if(url.pathname==='/api/state'&&req.method==='GET')return json(res,200,state(),origin);
 if(url.pathname==='/api/player-best'&&req.method==='GET'){const pid=cleanId(url.searchParams.get('playerId'));return pid?json(res,200,{ok:true,best:bestForPlayer(pid)},origin):json(res,400,{ok:false,error:'playerId required'},origin)}
 if(url.pathname==='/api/multiplayer/create'&&req.method==='POST')try{const b=await body(req),r=createRoom(b),p=r.players[0];broadcast();return json(res,200,{ok:true,room:summary(r),hostToken:r.hostToken,playerToken:p.token},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/multiplayer/join'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r||r.status!=='lobby')return json(res,404,{ok:false,error:'Open game not found'},origin);const pid=cleanId(b.playerId),name=cleanName(b.name);if(!pid)return json(res,400,{ok:false,error:'playerId required'},origin);let p=r.players.find(x=>x.playerId===pid);if(!p){if(r.players.length>=r.targetPlayers)return json(res,409,{ok:false,error:'Game is full'},origin);if(r.players.some(x=>x.name.toLowerCase()===name.toLowerCase()))return json(res,409,{ok:false,error:'Choose a different Arcade Name for this game'},origin);p={playerId:pid,name,seat:r.players.length+1,role:'guest',token:id('player')};r.players.push(p)}else p.name=name;r.lastEventAt=now();broadcastRoom(r,{type:'lobby-update',room:summary(r)});broadcast();return json(res,200,{ok:true,room:summary(r),playerToken:p.token},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/multiplayer/start'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r)return json(res,404,{ok:false,error:'Game not found'},origin);if(String(b.hostToken||'')!==r.hostToken)return json(res,403,{ok:false,error:'Host authorization required'},origin);if(r.status!=='lobby')return json(res,409,{ok:false,error:'Game already started'},origin);if(r.players.length!==r.targetPlayers)return json(res,409,{ok:false,error:`Waiting for ${r.targetPlayers-r.players.length} more player(s)`},origin);r.status='live';r.startedAt=now();r.currentPlayerId=r.players[0].playerId;r.currentPlayerName=r.players[0].name;r.currentSeat=1;r.secondsRemaining=60;broadcastRoom(r,{type:'room-started',room:summary(r)});broadcast();return json(res,200,{ok:true,room:summary(r)},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/start'&&req.method==='POST')try{const b=await body(req),names=(Array.isArray(b.playerNames)?b.playerNames:[]).map(cleanName).filter(Boolean).slice(0,4),r=createRoom({hostPlayerId:b.hostPlayerId,hostName:b.hostName||names[0],targetPlayers:Math.max(2,names.length||2)},'local');r.players=names.length?names.map((name,i)=>({playerId:i===0?cleanId(b.hostPlayerId):`local_${i}_${crypto.randomBytes(4).toString('hex')}`,name,seat:i+1,role:i===0?'host':'local',token:''})):r.players;r.targetPlayers=r.players.length;r.status='live';r.startedAt=now();r.currentPlayerId=r.players[0].playerId;r.currentPlayerName=r.players[0].name;r.currentSeat=1;broadcast();return json(res,200,{ok:true,room:summary(r),hostToken:r.hostToken},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/event'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r||r.status!=='live')return json(res,404,{ok:false,error:'Live game not found'},origin);const p=authPlayer(r,b);if(!p)return json(res,403,{ok:false,error:'Game authorization required'},origin);const ev=b.event&&typeof b.event==='object'?b.event:{},actor=cleanId(ev.playerId||ev.clientId||p.playerId);if(p.role!=='host'&&actor&&actor!==p.playerId)return json(res,403,{ok:false,error:'Player event ownership mismatch'},origin);if(['aim-event','shot-event','reward-event','turn-ended','game-state','player-stats'].includes(ev.type)&&p.role!=='host'&&p.playerId!==r.currentPlayerId)return json(res,403,{ok:false,error:'Not current player'},origin);if(['snapshot','turn-started','match-restart','lobby-reset'].includes(ev.type)&&p.role!=='host')return json(res,403,{ok:false,error:'Host event required'},origin);if(ev.type==='turn-started'){const seat=Math.max(1,Math.min(r.players.length,Number(ev.currentSeat)||1)),rp=r.players[seat-1];r.currentSeat=seat;r.currentPlayerId=cleanId(ev.activePlayerId||rp?.playerId);r.currentPlayerName=cleanName(ev.currentPlayerName||rp?.name)}if(Number.isFinite(Number(ev.secondsRemaining)))r.secondsRemaining=Math.max(0,Math.min(60,Math.ceil(Number(ev.secondsRemaining))));broadcastRoom(r,ev);if(['turn-started','turn-ended','snapshot'].includes(ev.type))broadcast();return json(res,200,{ok:true,seq:r.eventSeq},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/end'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r)return json(res,200,{ok:true,alreadyEnded:true},origin);if(String(b.hostToken||'')!==r.hostToken)return json(res,403,{ok:false,error:'Host authorization required'},origin);r.status='ended';broadcastRoom(r,{type:'room-ended'});broadcast();return json(res,200,{ok:true},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/stream'&&req.method==='GET'){const r=rooms.get(cleanId(url.searchParams.get('roomId')));if(!r||r.status==='ended')return json(res,404,{ok:false,error:'Game not found'},origin);res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','access-control-allow-origin':origin,'x-accel-buffering':'no'});res.write(': connected\n\n');const c={id:id('roomclient'),res,lastSeen:now(),closed:false};if(!roomClients.has(r.id))roomClients.set(r.id,new Map());roomClients.get(r.id).set(c.id,c);sse(c,{type:'bootstrap',room:summary(r),events:r.recentEvents.slice(-40)});broadcast();const timer=setInterval(()=>{c.lastSeen=now();sse(c,{type:'ping',at:now()})},15000);res.on('close',()=>{clearInterval(timer);c.closed=true;roomClients.get(r.id)?.delete(c.id);if(roomClients.get(r.id)?.size===0)roomClients.delete(r.id);broadcast()});return}
 if(url.pathname==='/api/admin/clear-scores'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);scores.length=0;seenRuns.clear();rewriteScores();broadcast();return json(res,200,{ok:true,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/admin/delete-score'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);const i=scores.findIndex(r=>r.id===cleanId(b.scoreId));if(i<0)return json(res,404,{ok:false,error:'Score not found'},origin);const removed=scores.splice(i,1)[0];seenRuns.clear();for(const r of scores)if(r.runId)seenRuns.add(r.runId);rewriteScores();broadcast();return json(res,200,{ok:true,removed,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/live'&&req.method==='GET'){const c={id:id('presence'),playerId:cleanId(url.searchParams.get('playerId'))||id('anon'),name:cleanName(url.searchParams.get('name')),res,lastSeen:now(),closed:false};res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','access-control-allow-origin':origin,'x-accel-buffering':'no'});res.write(': connected\n\n');clients.set(c.id,c);sse(c,{type:'state',state:state()});broadcast();const timer=setInterval(()=>{c.lastSeen=now();sse(c,{type:'ping',at:now()})},15000);res.on('close',()=>{clearInterval(timer);c.closed=true;clients.delete(c.id);broadcast()});return}
 if(url.pathname==='/api/score'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),name=cleanName(b.name),runId=cleanId(b.runId)||id('run'),score=Math.max(0,Math.min(CONFIG.maxScore,Math.floor(Number(b.score)||0)));if(!pid)return json(res,400,{ok:false,error:'playerId required'},origin);if(seenRuns.has(runId))return json(res,200,{ok:true,duplicate:true,state:state()},origin);const r={id:id('score'),playerId:pid,name,score,game:'shooting-gallery',runId,createdAt:new Date().toISOString(),stats:b.stats&&typeof b.stats==='object'?b.stats:{}};saveScore(r);broadcast();return json(res,200,{ok:true,result:r,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/join'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),name=cleanName(b.name);if(!pid)return json(res,400,{ok:false,error:'playerId required'},origin);const q=queueJoin(pid,name);broadcast();return json(res,200,{ok:true,entry:q,position:duelQueue.findIndex(x=>x.playerId===pid)+1,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/heartbeat'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),q=duelQueue.find(x=>x.playerId===pid);if(q)q.lastSeen=now();return json(res,200,{ok:true,position:q?duelQueue.indexOf(q)+1:0,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/leave'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),i=duelQueue.findIndex(x=>x.playerId===pid);if(i>=0)duelQueue.splice(i,1);broadcast();return json(res,200,{ok:true,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/')return json(res,200,{ok:true,service:'Medley Arcade Website Live Authority',build:CONFIG.build,health:'/health'},origin);res.writeHead(404,{'content-type':'text/plain; charset=utf-8','access-control-allow-origin':origin});res.end('Not found')});
setInterval(()=>{prune();broadcast()},30000);server.listen(PORT,'0.0.0.0',()=>console.log(`Medley_Arcade_Website_Live_094 Authority listening on ${PORT}`));
