'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA=path.resolve(process.env.DATA_DIR||path.join(ROOT,'data'));
const CONFIG=JSON.parse(fs.readFileSync(path.join(ROOT,'config.json'),'utf8'));
fs.mkdirSync(DATA,{recursive:true});
const PORT=Number(process.env.PORT)||10000;
const SCORE_FILE=path.join(DATA,'scores.jsonl');
const scores=[]; const seenRuns=new Set();
try{if(fs.existsSync(SCORE_FILE)){for(const line of fs.readFileSync(SCORE_FILE,'utf8').split(/\r?\n/)){if(!line.trim())continue;try{const r=JSON.parse(line);scores.push(r);if(r.runId)seenRuns.add(r.runId)}catch{}}}}catch{}
const clients=new Map(); const duelQueue=[]; let revision=1;
const liveRooms=new Map(); const roomClients=new Map();
const LIVE_TTL_MS=Math.max(120000,Number(CONFIG.liveGameTtlSeconds||900)*1000);
function cleanName(v){return String(v||'PLAYER').replace(/<[^>]*>/g,'').replace(/[^a-zA-Z0-9 ._\-'’]/g,'').replace(/\s+/g,' ').trim().slice(0,20)||'PLAYER'}
function cleanId(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100)}
function now(){return Date.now()} function id(prefix){return prefix+'_'+crypto.randomBytes(8).toString('hex')}
function leaderboard(){const map=new Map();for(const r of scores){const key=(r.playerId||r.name.toLowerCase());const prev=map.get(key);if(!prev||r.score>prev.score)map.set(key,r)}return [...map.values()].sort((a,b)=>b.score-a.score||new Date(a.createdAt)-new Date(b.createdAt)).slice(0,100)}
function recentScores(){return scores.slice(-12).reverse().map(r=>({name:r.name,score:r.score,createdAt:r.createdAt}))}
function roomWatchers(roomId){return roomClients.get(roomId)?.size||0}
function liveSummary(room){return {id:room.id,game:room.game,status:room.status,hostPlayerId:room.hostPlayerId,hostName:room.hostName,playerNames:room.playerNames,playerCount:room.playerNames.length,currentPlayerName:room.currentPlayerName,currentSeat:room.currentSeat,secondsRemaining:room.secondsRemaining,startedAt:room.startedAt,lastEventAt:room.lastEventAt,watchers:roomWatchers(room.id)}}
function activeLiveGames(){pruneRooms();return [...liveRooms.values()].filter(r=>r.status==='live').sort((a,b)=>b.startedAt-a.startedAt).map(liveSummary)}
function pruneRooms(){const t=now();for(const [rid,r] of liveRooms){if(r.status!=='live'||t-r.lastEventAt>LIVE_TTL_MS){r.status='ended';const viewers=roomClients.get(rid);if(viewers){for(const c of viewers.values()){try{sse(c,{type:'room-ended',roomId:rid})}catch{}try{c.res.end()}catch{}}roomClients.delete(rid)}if(t-r.lastEventAt>LIVE_TTL_MS*2)liveRooms.delete(rid)}}}
function prune(){const t=now();for(let i=duelQueue.length-1;i>=0;i--)if(t-duelQueue[i].lastSeen>CONFIG.duelWaitTtlSeconds*1000)duelQueue.splice(i,1);for(const [k,c] of clients)if(c.closed||t-c.lastSeen>CONFIG.presenceTtlSeconds*1000){try{c.res.end()}catch{}clients.delete(k)}pruneRooms()}
function publicState(){prune();return{build:CONFIG.build,revision,online:clients.size,leaderboard:leaderboard().slice(0,10),recent:recentScores(),duel:{waiting:duelQueue.length,names:duelQueue.slice(0,5).map(x=>x.name)},liveGames:activeLiveGames()}}
function json(res,status,obj,origin='*'){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(obj))}
function allowedOrigin(req){const o=req.headers.origin||'';if(!o)return '*';const env=process.env.PUBLIC_SITE_URL;if(env&&o===env)return o;return CONFIG.allowedOrigins.includes(o)?o:'null'}
function sse(c,payload){if(c.closed)return;try{c.res.write(`data: ${JSON.stringify(payload)}\n\n`)}catch{c.closed=true}}
function broadcast(){revision++;const state=publicState();for(const c of clients.values())sse(c,{type:'state',state})}
function broadcastRoom(room,payload){room.lastEventAt=now();room.eventSeq++;const event={...payload,roomId:room.id,seq:room.eventSeq,serverAt:now()};room.recentEvents.push(event);if(room.recentEvents.length>80)room.recentEvents.shift();if(['snapshot','game-state','turn-started','player-stats','match-restart','lobby-reset'].includes(event.type))room.latest[event.type]=event;const viewers=roomClients.get(room.id);if(viewers)for(const c of viewers.values())sse(c,{type:'game-event',event});}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>350000){reject(Error('Too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Error('Bad JSON'))}})})}
function rewriteScores(){fs.writeFileSync(SCORE_FILE,scores.map(r=>JSON.stringify(r)).join('\n')+(scores.length?'\n':''))}
function saveScore(r){scores.push(r);seenRuns.add(r.runId);while(scores.length>CONFIG.maxScores)scores.shift();fs.appendFileSync(SCORE_FILE,JSON.stringify(r)+'\n')}
function bestForPlayer(playerId){const rows=scores.filter(r=>r.playerId===playerId).sort((a,b)=>b.score-a.score||new Date(a.createdAt)-new Date(b.createdAt));return rows[0]||null}
function hostAuthorized(b){return String(b?.hostCode||'')===String(process.env.HOST_CODE||'host4536')}
function queueJoin(playerId,name){const existing=duelQueue.find(x=>x.playerId===playerId);if(existing){existing.name=name;existing.lastSeen=now();return existing}const row={id:id('duel'),playerId,name,joinedAt:now(),lastSeen:now()};duelQueue.push(row);return row}
function liveRoomAuthorized(room,b){return room&&String(b?.hostToken||'')===room.hostToken}
function createLiveRoom(b){const names=(Array.isArray(b.playerNames)?b.playerNames:[]).map(cleanName).filter(Boolean).slice(0,4);if(!names.length)names.push(cleanName(b.hostName));const room={id:id('live'),hostToken:id('host'),game:'shooting-gallery',hostPlayerId:cleanId(b.hostPlayerId),hostName:cleanName(b.hostName||names[0]),playerNames:names,status:'live',currentPlayerName:names[0],currentSeat:1,secondsRemaining:60,startedAt:now(),lastEventAt:now(),eventSeq:0,recentEvents:[],latest:{}};liveRooms.set(room.id,room);return room}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');const origin=allowedOrigin(req);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});return res.end()}
 if(url.pathname==='/health')return json(res,200,{ok:true,service:'Medley Arcade Website Live Authority',build:CONFIG.build,state:publicState()},origin);
 if(url.pathname==='/api/state'&&req.method==='GET')return json(res,200,publicState(),origin);
 if(url.pathname==='/api/player-best'&&req.method==='GET'){const playerId=cleanId(url.searchParams.get('playerId'));if(!playerId)return json(res,400,{ok:false,error:'playerId required'},origin);return json(res,200,{ok:true,best:bestForPlayer(playerId)},origin)}
 if(url.pathname==='/api/live-game/start'&&req.method==='POST')try{const b=await body(req);const room=createLiveRoom(b);broadcast();return json(res,200,{ok:true,room:liveSummary(room),hostToken:room.hostToken},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/event'&&req.method==='POST')try{const b=await body(req),room=liveRooms.get(cleanId(b.roomId));if(!room||room.status!=='live')return json(res,404,{ok:false,error:'Live game not found'},origin);if(!liveRoomAuthorized(room,b))return json(res,403,{ok:false,error:'Live game authorization required'},origin);const ev=b.event&&typeof b.event==='object'?b.event:{};if(ev.type==='turn-started'){const seat=Math.max(1,Math.min(4,Number(ev.currentSeat)||Number(ev.seat)||room.currentSeat||1));room.currentSeat=seat;room.currentPlayerName=cleanName(ev.currentPlayerName||room.playerNames[seat-1]||room.currentPlayerName)}if(Number.isFinite(Number(ev.secondsRemaining)))room.secondsRemaining=Math.max(0,Math.min(60,Math.ceil(Number(ev.secondsRemaining))));broadcastRoom(room,ev);if(ev.type==='turn-started'||ev.type==='turn-ended'||ev.type==='snapshot')broadcast();return json(res,200,{ok:true,seq:room.eventSeq},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/end'&&req.method==='POST')try{const b=await body(req),room=liveRooms.get(cleanId(b.roomId));if(!room)return json(res,200,{ok:true,alreadyEnded:true},origin);if(!liveRoomAuthorized(room,b))return json(res,403,{ok:false,error:'Live game authorization required'},origin);room.status='ended';room.lastEventAt=now();broadcastRoom(room,{type:'room-ended'});broadcast();return json(res,200,{ok:true},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/stream'&&req.method==='GET'){
   const roomId=cleanId(url.searchParams.get('roomId')),room=liveRooms.get(roomId);if(!room||room.status!=='live')return json(res,404,{ok:false,error:'Live game not found'},origin);
   res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','access-control-allow-origin':origin,'x-accel-buffering':'no'});res.write(': connected\n\n');
   const c={id:id('viewer'),res,lastSeen:now(),closed:false};if(!roomClients.has(roomId))roomClients.set(roomId,new Map());roomClients.get(roomId).set(c.id,c);
   sse(c,{type:'bootstrap',room:liveSummary(room),events:room.recentEvents.slice(-30)});broadcast();
   const timer=setInterval(()=>{c.lastSeen=now();sse(c,{type:'ping',at:now()})},15000);res.on('close',()=>{clearInterval(timer);c.closed=true;roomClients.get(roomId)?.delete(c.id);if(roomClients.get(roomId)?.size===0)roomClients.delete(roomId);broadcast()});return;
 }
 if(url.pathname==='/api/admin/clear-scores'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);scores.length=0;seenRuns.clear();rewriteScores();broadcast();return json(res,200,{ok:true,cleared:true,state:publicState()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/admin/delete-score'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);const scoreId=cleanId(b.scoreId);if(!scoreId)return json(res,400,{ok:false,error:'scoreId required'},origin);const i=scores.findIndex(r=>r.id===scoreId);if(i<0)return json(res,404,{ok:false,error:'Score not found'},origin);const removed=scores.splice(i,1)[0];seenRuns.clear();for(const r of scores)if(r.runId)seenRuns.add(r.runId);rewriteScores();broadcast();return json(res,200,{ok:true,removed,state:publicState()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/live'&&req.method==='GET'){
   const playerId=cleanId(url.searchParams.get('playerId'))||id('anon'),name=cleanName(url.searchParams.get('name'));
   res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','access-control-allow-origin':origin,'x-accel-buffering':'no'});res.write(': connected\n\n');
   const c={id:id('presence'),playerId,name,res,lastSeen:now(),closed:false};clients.set(c.id,c);sse(c,{type:'state',state:publicState()});broadcast();
   const timer=setInterval(()=>{c.lastSeen=now();sse(c,{type:'ping',at:now()})},15000);res.on('close',()=>{clearInterval(timer);c.closed=true;clients.delete(c.id);broadcast()});return;
 }
 if(url.pathname==='/api/score'&&req.method==='POST')try{const b=await body(req),playerId=cleanId(b.playerId),name=cleanName(b.name),runId=cleanId(b.runId)||id('run'),score=Math.max(0,Math.min(CONFIG.maxScore,Math.floor(Number(b.score)||0)));if(!playerId)return json(res,400,{ok:false,error:'playerId required'},origin);if(seenRuns.has(runId))return json(res,200,{ok:true,duplicate:true,state:publicState()},origin);const r={id:id('score'),playerId,name,score,game:'shooting-gallery',runId,createdAt:new Date().toISOString(),stats:b.stats&&typeof b.stats==='object'?b.stats:{}};saveScore(r);broadcast();return json(res,200,{ok:true,result:r,state:publicState()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/join'&&req.method==='POST')try{const b=await body(req),playerId=cleanId(b.playerId),name=cleanName(b.name);if(!playerId)return json(res,400,{ok:false,error:'playerId required'},origin);const row=queueJoin(playerId,name);broadcast();return json(res,200,{ok:true,entry:row,position:duelQueue.findIndex(x=>x.playerId===playerId)+1,state:publicState()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/heartbeat'&&req.method==='POST')try{const b=await body(req),playerId=cleanId(b.playerId),q=duelQueue.find(x=>x.playerId===playerId);if(q)q.lastSeen=now();return json(res,200,{ok:true,position:q?duelQueue.indexOf(q)+1:0,state:publicState()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/leave'&&req.method==='POST')try{const b=await body(req),playerId=cleanId(b.playerId),i=duelQueue.findIndex(x=>x.playerId===playerId);if(i>=0)duelQueue.splice(i,1);broadcast();return json(res,200,{ok:true,state:publicState()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/'){return json(res,200,{ok:true,service:'Medley Arcade Website Live Authority',build:CONFIG.build,health:'/health'},origin)}
 res.writeHead(404,{'content-type':'text/plain; charset=utf-8','access-control-allow-origin':origin});res.end('Not found');
});
setInterval(()=>{prune();broadcast()},30000);
server.listen(PORT,'0.0.0.0',()=>console.log(`Medley_Arcade_Website_Live_093 Authority listening on ${PORT}`));
