'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,CONFIG=JSON.parse(fs.readFileSync(path.join(ROOT,'config.json'),'utf8'));
function resolveDataDir(){if(process.env.DATA_DIR)return path.resolve(process.env.DATA_DIR);try{if(fs.existsSync('/var/data')){fs.accessSync('/var/data',fs.constants.W_OK);return '/var/data/medley-arcade'}}catch{}return path.join(ROOT,'data')}
const DATA=path.resolve(resolveDataDir());fs.mkdirSync(DATA,{recursive:true});
const PORT=Number(process.env.PORT)||10000,SCORE_FILE=path.join(DATA,'scores.jsonl'),VOTE_FILE=path.join(DATA,'community-votes.json'),IDEA_FILE=path.join(DATA,'community-suggestions.json'),scores=[],seenRuns=new Set(),clients=new Map(),duelQueue=[],rooms=new Map(),roomClients=new Map();let revision=1;
const GAME_IDS=new Set(['shooting','memory','second','slotcar','word','track']);
let communityVotes={season:{number:1,startedAt:new Date().toISOString()},ballots:0,games:{},voters:{},history:[]};
let communityIdeas=[];

function readJsonFile(file,fallback){try{if(!fs.existsSync(file))return fallback;const raw=fs.readFileSync(file,'utf8');return raw.trim()?JSON.parse(raw):fallback}catch(e){console.warn('Persistent JSON load skipped:',path.basename(file),e&&e.message?e.message:e);return fallback}}
function writeJsonAtomic(file,value){const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(value,null,2));fs.renameSync(tmp,file)}
function normalizeVoteState(v){v=v&&typeof v==='object'?v:{};const season=v.season&&Number(v.season.number)>=1?v.season:{number:1,startedAt:new Date().toISOString()};const games={};for(const id of GAME_IDS){const n=Math.max(0,Math.floor(Number(v.games?.[id]?.votes??v.games?.[id]??0)));if(n)games[id]={votes:n}}return{season:{number:Number(season.number)||1,startedAt:season.startedAt||new Date().toISOString()},ballots:Math.max(0,Math.floor(Number(v.ballots)||0)),games,voters:v.voters&&typeof v.voters==='object'?v.voters:{},history:Array.isArray(v.history)?v.history.slice(0,24):[]}}
function cleanIdeaText(v,max=1200){return String(v||'').replace(/<[^>]*>/g,'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function cleanIdeaKind(v){return cleanIdeaText(v,60)||'Player Idea'}
function cleanIdeaGame(v){return cleanIdeaText(v,60)||'Shooting Gallery'}
function loadCommunitySafely(){communityVotes=normalizeVoteState(readJsonFile(VOTE_FILE,communityVotes));const raw=readJsonFile(IDEA_FILE,[]);communityIdeas=(Array.isArray(raw)?raw:[]).filter(x=>x&&x.idea).slice(0,500);console.log(`Loaded community data: ${communityVotes.ballots} ballot(s), ${communityIdeas.length} suggestion(s)`)}
function saveCommunityVotes(){writeJsonAtomic(VOTE_FILE,communityVotes)}
function saveCommunityIdeas(){writeJsonAtomic(IDEA_FILE,communityIdeas)}
function publicVotes(){return{season:communityVotes.season,ballots:communityVotes.ballots,games:communityVotes.games}}
function publicIdeas(){return communityIdeas.filter(x=>!x.hidden).slice().sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,100)}
function persistentConfigured(){return !DATA.startsWith(ROOT+path.sep)}
function loadScoresSafely(){try{if(!fs.existsSync(SCORE_FILE))return;const st=fs.statSync(SCORE_FILE);if(st.size>8*1024*1024){console.warn('Score file exceeds safe startup load limit; starting without preload');return}for(const line of fs.readFileSync(SCORE_FILE,'utf8').split(/\r?\n/)){if(!line.trim())continue;try{const r=JSON.parse(line);scores.push(r);if(r.runId)seenRuns.add(r.runId)}catch{}}console.log(`Loaded ${scores.length} saved score(s)`)}catch(e){console.warn('Score preload skipped:',e&&e.message?e.message:e)}}
const now=()=>Date.now(),id=p=>p+'_'+crypto.randomBytes(8).toString('hex');
function cleanName(v){return String(v||'PLAYER').replace(/<[^>]*>/g,'').replace(/[^a-zA-Z0-9 ._\-'’]/g,'').replace(/\s+/g,' ').trim().slice(0,20)||'PLAYER'}
function cleanId(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100)}
function allowedOrigin(req){const o=req.headers.origin||'';if(!o)return '*';const env=process.env.PUBLIC_SITE_URL;if(env&&o===env)return o;return CONFIG.allowedOrigins.includes(o)?o:'null'}
function json(res,status,obj,origin='*'){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(obj))}
function sse(c,p){if(c.closed)return;try{c.res.write(`data: ${JSON.stringify(p)}\n\n`)}catch{c.closed=true}}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>350000){reject(Error('Too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Error('Bad JSON'))}})})}
function leaderboard(){const map=new Map();for(const r of scores){const k=r.playerId||r.name.toLowerCase(),p=map.get(k);if(!p||r.score>p.score)map.set(k,r)}return [...map.values()].sort((a,b)=>b.score-a.score||new Date(a.createdAt)-new Date(b.createdAt)).slice(0,100)}
function recentScores(){return scores.slice(-12).reverse().map(r=>({name:r.name,score:r.score,createdAt:r.createdAt}))}
function rewriteScores(){fs.writeFileSync(SCORE_FILE,scores.map(r=>JSON.stringify(r)).join('\n')+(scores.length?'\n':''))}
function saveScore(r){scores.push(r);seenRuns.add(r.runId);while(scores.length>CONFIG.maxScores)scores.shift();fs.appendFileSync(SCORE_FILE,JSON.stringify(r)+'\n')}
function bestForPlayer(pid){return scores.filter(r=>r.playerId===pid).sort((a,b)=>b.score-a.score||new Date(a.createdAt)-new Date(b.createdAt))[0]||null}
function hostAuthorized(b){return String(b?.hostCode||'')===String(process.env.HOST_CODE||'host4536')}
function queueJoin(pid,name){let q=duelQueue.find(x=>x.playerId===pid);if(q){q.name=name;q.lastSeen=now();return q}q={id:id('duel'),playerId:pid,name,joinedAt:now(),lastSeen:now()};duelQueue.push(q);return q}
function makeCode(){let c;do{c=String(Math.floor(100000+Math.random()*900000))}while([...rooms.values()].some(r=>r.joinCode===c&&r.status!=='ended'));return c}
function publicPlayers(r){return r.players.map(p=>({playerId:p.playerId,name:p.name,seat:p.seat,role:p.role,ready:true}))}
function summary(r){return{id:r.id,joinCode:r.joinCode,game:'shooting-gallery',mode:r.mode,status:r.status,hostPlayerId:r.hostPlayerId,hostName:r.hostName,targetPlayers:r.targetPlayers,players:publicPlayers(r),playerNames:r.players.map(p=>p.name),playerCount:r.players.length,currentPlayerId:r.currentPlayerId,currentPlayerName:r.currentPlayerName,currentSeat:r.currentSeat,secondsRemaining:r.secondsRemaining,createdAt:r.createdAt,startedAt:r.startedAt,lastEventAt:r.lastEventAt,watchers:roomClients.get(r.id)?.size||0,canStart:r.status==='lobby'&&r.players.length===r.targetPlayers,rematch:r.rematch?{deadline:r.rematch.deadline,votes:[...r.rematch.votes],eligiblePlayerIds:r.rematch.eligiblePlayerIds||[],nextRoomId:r.rematch.nextRoomId||'',startAt:r.rematch.startAt||0}:null,sourceRoomId:r.sourceRoomId||'',rematchStartAt:r.rematchStartAt||0}}
function roomBy(b){const rid=cleanId(b.roomId);if(rid&&rooms.has(rid))return rooms.get(rid);const code=String(b.joinCode||'').replace(/\D/g,'').slice(0,6);return [...rooms.values()].find(r=>r.joinCode===code&&r.status!=='ended')||null}
function createRoom(b,mode='online'){const pid=cleanId(b.hostPlayerId),name=cleanName(b.hostName),target=Math.max(2,Math.min(4,Number(b.targetPlayers)||2));if(!pid)throw Error('hostPlayerId required');const r={id:id('room'),joinCode:makeCode(),mode,status:'lobby',hostToken:id('host'),hostPlayerId:pid,hostName:name,targetPlayers:target,players:[{playerId:pid,name,seat:1,role:'host',token:id('player')}],currentPlayerId:'',currentPlayerName:'',currentSeat:0,secondsRemaining:60,createdAt:now(),startedAt:0,lastEventAt:now(),eventSeq:0,recentEvents:[]};rooms.set(r.id,r);return r}

function retireHostedLobbies(pid,reason='replaced'){
  pid=cleanId(pid); if(!pid)return 0; let n=0;
  for(const r of rooms.values()){
    if(r.mode==='online'&&r.status==='lobby'&&r.hostPlayerId===pid){
      r.status='ended'; r.lastEventAt=now(); n++;
      broadcastRoom(r,{type:'room-ended',reason});
    }
  }
  return n;
}
function leaveLobby(r,p,reason='left'){
  if(!r||r.status!=='lobby'||!p)return false;
  if(p.role==='host'||p.playerId===r.hostPlayerId){
    r.status='ended'; r.lastEventAt=now(); broadcastRoom(r,{type:'room-ended',reason}); return true;
  }
  r.players=r.players.filter(x=>x.playerId!==p.playerId);
  r.players.forEach((x,i)=>x.seat=i+1);
  r.lastEventAt=now(); broadcastRoom(r,{type:'lobby-update',room:summary(r),reason}); return true;
}
function authPlayer(r,b){if(!r)return null;if(String(b.hostToken||'')===r.hostToken)return r.players.find(p=>p.playerId===r.hostPlayerId);const pid=cleanId(b.playerId),tok=String(b.playerToken||'');return r.players.find(p=>p.playerId===pid&&p.token===tok)||null}
function broadcastRoom(r,payload){r.lastEventAt=now();const ev={...payload,roomId:r.id,seq:++r.eventSeq,serverAt:now()};r.recentEvents.push(ev);if(r.recentEvents.length>120)r.recentEvents.shift();const set=roomClients.get(r.id);if(set)for(const c of set.values())sse(c,{type:'game-event',event:ev})}
function cleanResults(v){return(Array.isArray(v)?v:[]).slice(0,4).map((x,i)=>({playerId:cleanId(x?.playerId),name:cleanName(x?.name||`Player ${i+1}`),seat:Math.max(1,Math.min(4,Number(x?.seat)||i+1)),score:Math.max(0,Math.min(CONFIG.maxScore,Math.floor(Number(x?.score)||0)))})).sort((a,b)=>b.score-a.score||a.seat-b.seat)}
function openRematch(r,results){if(!r.rematch){r.rematch={deadline:now()+15000,votes:new Set(),results:cleanResults(results),eligiblePlayerIds:[],nextRoomId:'',startAt:0}}else if(results?.length)r.rematch.results=cleanResults(results);r.status='results';r.lastEventAt=now();return r.rematch}
function finalizeRematch(r){if(!r.rematch||r.rematch.nextRoomId)return;const opted=r.players.filter(p=>r.rematch.votes.has(p.playerId));r.rematch.eligiblePlayerIds=opted.map(p=>p.playerId);if(opted.length<2){r.status='ended';broadcastRoom(r,{type:'rematch-cancelled',reason:'not-enough-players',results:r.rematch.results||[]});broadcastRoom(r,{type:'room-ended',reason:'rematch-complete'});broadcast();return}const nr={id:id('room'),joinCode:makeCode(),mode:'online',status:'rematch-countdown',hostToken:id('host'),hostPlayerId:opted[0].playerId,hostName:opted[0].name,targetPlayers:opted.length,players:opted.map((p,i)=>({playerId:p.playerId,name:p.name,seat:i+1,role:i===0?'host':'guest',token:id('player')})),currentPlayerId:'',currentPlayerName:'',currentSeat:0,secondsRemaining:60,createdAt:now(),startedAt:0,lastEventAt:now(),eventSeq:0,recentEvents:[],sourceRoomId:r.id,rematchStartAt:now()+3000};rooms.set(nr.id,nr);r.rematch.nextRoomId=nr.id;r.rematch.startAt=nr.rematchStartAt;r.status='ended';broadcastRoom(r,{type:'rematch-ready',nextRoom:summary(nr),eligiblePlayerIds:r.rematch.eligiblePlayerIds,startAt:nr.rematchStartAt,results:r.rematch.results||[]});broadcast()}
function advanceRematches(){const t=now();for(const r of rooms.values()){if(r.status==='results'&&r.rematch&&t>=r.rematch.deadline)finalizeRematch(r);if(r.status==='rematch-countdown'&&r.rematchStartAt&&t>=r.rematchStartAt){r.status='live';r.startedAt=t;r.currentSeat=1;r.currentPlayerId=r.players[0]?.playerId||'';r.currentPlayerName=r.players[0]?.name||'';r.secondsRemaining=60;broadcastRoom(r,{type:'room-started',room:summary(r),rematch:true});broadcast()}}}
function prune(){const t=now(),liveT=Math.max(120000,Number(CONFIG.liveGameTtlSeconds||900)*1000),lobbyT=Math.max(45000,Number(CONFIG.multiplayerLobbyHeartbeatTtlSeconds||90)*1000);for(let i=duelQueue.length-1;i>=0;i--)if(t-duelQueue[i].lastSeen>CONFIG.duelWaitTtlSeconds*1000)duelQueue.splice(i,1);for(const [k,c] of clients)if(c.closed||t-c.lastSeen>CONFIG.presenceTtlSeconds*1000){try{c.res.end()}catch{}clients.delete(k)}for(const [rid,r] of rooms){const ttl=r.status==='lobby'?lobbyT:liveT;if(r.status!=='ended'&&t-r.lastEventAt>ttl){r.status='ended';broadcastRoom(r,{type:'room-ended',reason:'expired'})}if(r.status==='ended'&&t-r.lastEventAt>ttl*2){rooms.delete(rid);roomClients.delete(rid)}}}
function state(){prune();return{build:CONFIG.build,persistence:{dataDir:DATA,durable:persistentConfigured()},community:{ballots:communityVotes.ballots,suggestions:communityIdeas.length,season:communityVotes.season.number},revision,online:clients.size,leaderboard:leaderboard().slice(0,10),recent:recentScores(),duel:{waiting:duelQueue.length,names:duelQueue.slice(0,5).map(x=>x.name)},liveGames:[...rooms.values()].filter(r=>r.status==='live').sort((a,b)=>b.startedAt-a.startedAt).map(summary),openGames:[...rooms.values()].filter(r=>r.status==='lobby').sort((a,b)=>b.createdAt-a.createdAt).map(summary)}}
function broadcast(){revision++;const st=state();for(const c of clients.values())sse(c,{type:'state',state:st})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'),origin=allowedOrigin(req);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});return res.end()}
 if(url.pathname==='/health')return json(res,200,{ok:true,service:'Medley Arcade Website Live Authority',build:CONFIG.build,state:state()},origin);
 if(url.pathname==='/api/state'&&req.method==='GET')return json(res,200,state(),origin);
 if(url.pathname==='/api/player-best'&&req.method==='GET'){const pid=cleanId(url.searchParams.get('playerId'));return pid?json(res,200,{ok:true,best:bestForPlayer(pid)},origin):json(res,400,{ok:false,error:'playerId required'},origin)}
 if(url.pathname==='/api/multiplayer/create'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.hostPlayerId);retireHostedLobbies(pid,'replaced-by-new-room');const r=createRoom(b),p=r.players[0];broadcast();return json(res,200,{ok:true,room:summary(r),hostToken:r.hostToken,playerToken:p.token,replacedPrevious:true},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/multiplayer/join'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r||r.status!=='lobby')return json(res,404,{ok:false,error:'Open game not found'},origin);const pid=cleanId(b.playerId),name=cleanName(b.name);if(!pid)return json(res,400,{ok:false,error:'playerId required'},origin);let p=r.players.find(x=>x.playerId===pid);if(!p){if(r.players.length>=r.targetPlayers)return json(res,409,{ok:false,error:'Game is full'},origin);if(r.players.some(x=>x.name.toLowerCase()===name.toLowerCase()))return json(res,409,{ok:false,error:'Choose a different Arcade Name for this game'},origin);p={playerId:pid,name,seat:r.players.length+1,role:'guest',token:id('player')};r.players.push(p)}else p.name=name;r.lastEventAt=now();broadcastRoom(r,{type:'lobby-update',room:summary(r)});broadcast();return json(res,200,{ok:true,room:summary(r),playerToken:p.token},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/multiplayer/heartbeat'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r||r.status!=='lobby')return json(res,404,{ok:false,error:'Open game not found'},origin);const p=authPlayer(r,b);if(!p)return json(res,403,{ok:false,error:'Player authorization required'},origin);r.lastEventAt=now();return json(res,200,{ok:true,room:summary(r)},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/multiplayer/leave'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r)return json(res,200,{ok:true,alreadyGone:true},origin);const p=authPlayer(r,b);if(!p)return json(res,403,{ok:false,error:'Player authorization required'},origin);leaveLobby(r,p,'player-left-lobby');broadcast();return json(res,200,{ok:true},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/multiplayer/start'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r)return json(res,404,{ok:false,error:'Game not found'},origin);if(String(b.hostToken||'')!==r.hostToken)return json(res,403,{ok:false,error:'Host authorization required'},origin);if(r.status!=='lobby')return json(res,409,{ok:false,error:'Game already started'},origin);if(r.players.length!==r.targetPlayers)return json(res,409,{ok:false,error:`Waiting for ${r.targetPlayers-r.players.length} more player(s)`},origin);r.status='live';r.startedAt=now();r.currentPlayerId=r.players[0].playerId;r.currentPlayerName=r.players[0].name;r.currentSeat=1;r.secondsRemaining=60;broadcastRoom(r,{type:'room-started',room:summary(r)});broadcast();return json(res,200,{ok:true,room:summary(r)},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/start'&&req.method==='POST')try{const b=await body(req),names=(Array.isArray(b.playerNames)?b.playerNames:[]).map(cleanName).filter(Boolean).slice(0,4),r=createRoom({hostPlayerId:b.hostPlayerId,hostName:b.hostName||names[0],targetPlayers:Math.max(2,names.length||2)},'local');r.players=names.length?names.map((name,i)=>({playerId:i===0?cleanId(b.hostPlayerId):`local_${i}_${crypto.randomBytes(4).toString('hex')}`,name,seat:i+1,role:i===0?'host':'local',token:''})):r.players;r.targetPlayers=r.players.length;r.status='live';r.startedAt=now();r.currentPlayerId=r.players[0].playerId;r.currentPlayerName=r.players[0].name;r.currentSeat=1;broadcast();return json(res,200,{ok:true,room:summary(r),hostToken:r.hostToken},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/event'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r||r.status!=='live')return json(res,404,{ok:false,error:'Live game not found'},origin);const p=authPlayer(r,b);if(!p)return json(res,403,{ok:false,error:'Game authorization required'},origin);const ev=b.event&&typeof b.event==='object'?b.event:{},actor=cleanId(ev.playerId||ev.clientId||p.playerId);if(p.role!=='host'&&actor&&actor!==p.playerId)return json(res,403,{ok:false,error:'Player event ownership mismatch'},origin);if(['aim-event','shot-event','reward-event','turn-ended','game-state','player-stats'].includes(ev.type)&&p.role!=='host'&&p.playerId!==r.currentPlayerId)return json(res,403,{ok:false,error:'Not current player'},origin);if(['snapshot','turn-started','match-restart','lobby-reset'].includes(ev.type)&&p.role!=='host')return json(res,403,{ok:false,error:'Host event required'},origin);if(ev.type==='turn-started'){const seat=Math.max(1,Math.min(r.players.length,Number(ev.currentSeat)||1)),rp=r.players[seat-1];r.currentSeat=seat;r.currentPlayerId=cleanId(ev.activePlayerId||rp?.playerId);r.currentPlayerName=cleanName(ev.currentPlayerName||rp?.name)}if(Number.isFinite(Number(ev.secondsRemaining)))r.secondsRemaining=Math.max(0,Math.min(60,Math.ceil(Number(ev.secondsRemaining))));broadcastRoom(r,ev);if(['turn-started','turn-ended','snapshot'].includes(ev.type))broadcast();return json(res,200,{ok:true,seq:r.eventSeq},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/rematch/open'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r)return json(res,404,{ok:false,error:'Game not found'},origin);if(String(b.hostToken||'')!==r.hostToken)return json(res,403,{ok:false,error:'Host authorization required'},origin);const rm=openRematch(r,b.results);broadcastRoom(r,{type:'match-results',results:rm.results,deadline:rm.deadline,room:summary(r)});broadcast();return json(res,200,{ok:true,room:summary(r),results:rm.results,deadline:rm.deadline},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/rematch/vote'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r||r.status!=='results'||!r.rematch)return json(res,404,{ok:false,error:'Rematch window not found'},origin);const p=authPlayer(r,b);if(!p)return json(res,403,{ok:false,error:'Player authorization required'},origin);r.rematch.votes.add(p.playerId);r.lastEventAt=now();broadcastRoom(r,{type:'rematch-update',votes:[...r.rematch.votes],deadline:r.rematch.deadline,results:r.rematch.results||[]});return json(res,200,{ok:true,votes:[...r.rematch.votes],deadline:r.rematch.deadline},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/rematch/claim'&&req.method==='POST')try{const b=await body(req),old=rooms.get(cleanId(b.sourceRoomId)),nr=rooms.get(cleanId(b.nextRoomId));if(!old||!nr||nr.sourceRoomId!==old.id)return json(res,404,{ok:false,error:'Rematch not found'},origin);const pid=cleanId(b.playerId),tok=String(b.playerToken||''),oldp=old.players.find(p=>p.playerId===pid&&p.token===tok);if(!oldp)return json(res,403,{ok:false,error:'Player authorization required'},origin);const np=nr.players.find(p=>p.playerId===pid);if(!np)return json(res,403,{ok:false,error:'Player is not in this rematch'},origin);return json(res,200,{ok:true,room:summary(nr),playerToken:np.token,hostToken:np.role==='host'?nr.hostToken:'',role:np.role},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/end'&&req.method==='POST')try{const b=await body(req),r=roomBy(b);if(!r)return json(res,200,{ok:true,alreadyEnded:true},origin);if(String(b.hostToken||'')!==r.hostToken)return json(res,403,{ok:false,error:'Host authorization required'},origin);r.status='ended';broadcastRoom(r,{type:'room-ended'});broadcast();return json(res,200,{ok:true},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/live-game/stream'&&req.method==='GET'){const r=rooms.get(cleanId(url.searchParams.get('roomId')));if(!r||r.status==='ended')return json(res,404,{ok:false,error:'Game not found'},origin);res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','access-control-allow-origin':origin,'x-accel-buffering':'no'});res.write(': connected\n\n');const c={id:id('roomclient'),res,lastSeen:now(),closed:false};if(!roomClients.has(r.id))roomClients.set(r.id,new Map());roomClients.get(r.id).set(c.id,c);sse(c,{type:'bootstrap',room:summary(r),events:r.recentEvents.slice(-40)});broadcast();const timer=setInterval(()=>{c.lastSeen=now();sse(c,{type:'ping',at:now()})},15000);res.on('close',()=>{clearInterval(timer);c.closed=true;roomClients.get(r.id)?.delete(c.id);if(roomClients.get(r.id)?.size===0)roomClients.delete(r.id);broadcast()});return}

 if(url.pathname==='/api/community/votes'&&req.method==='GET'){const pid=cleanId(url.searchParams.get('playerId'));const voterKey=pid?(String(communityVotes.season.number)+':'+pid):'';return json(res,200,{ok:true,votes:publicVotes(),alreadyVoted:Boolean(voterKey&&communityVotes.voters[voterKey])},origin)}
 if(url.pathname==='/api/community/vote'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),picks=[...new Set((Array.isArray(b.picks)?b.picks:[]).map(cleanId))].filter(x=>GAME_IDS.has(x));if(!pid)return json(res,400,{ok:false,error:'playerId required'},origin);if(picks.length!==3)return json(res,400,{ok:false,error:'Choose exactly three different games'},origin);const voterKey=String(communityVotes.season.number)+':'+pid;if(communityVotes.voters[voterKey])return json(res,200,{ok:true,duplicate:true,votes:publicVotes(),alreadyVoted:true},origin);communityVotes.ballots++;for(const gid of picks){const row=communityVotes.games[gid]||(communityVotes.games[gid]={votes:0});row.votes=Math.max(0,Number(row.votes)||0)+1}communityVotes.voters[voterKey]={at:new Date().toISOString(),picks};saveCommunityVotes();return json(res,200,{ok:true,votes:publicVotes(),alreadyVoted:true},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/community/suggestions'&&req.method==='GET')return json(res,200,{ok:true,ideas:publicIdeas()},origin)
 if(url.pathname==='/api/community/suggestion'&&req.method==='POST')try{const b=await body(req),idea=cleanIdeaText(b.idea,1200),name=cleanName(b.name||'PLAYER'),game=cleanIdeaGame(b.game),kind=cleanIdeaKind(b.kind),pid=cleanId(b.playerId);if(idea.length<4)return json(res,400,{ok:false,error:'Suggestion is too short'},origin);if(communityIdeas.some(x=>cleanIdeaText(x.idea,1200).toLowerCase()===idea.toLowerCase()))return json(res,200,{ok:true,duplicate:true,ideas:publicIdeas()},origin);const item={id:id('idea'),playerId:pid,name:name==='PLAYER'&&!b.name?'':name,game,kind,idea,createdAt:new Date().toISOString(),hidden:false,implemented:false};communityIdeas.unshift(item);communityIdeas=communityIdeas.slice(0,500);saveCommunityIdeas();return json(res,200,{ok:true,item,ideas:publicIdeas()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/admin/replace-suggestions'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);const rows=Array.isArray(b.items)?b.items:[];communityIdeas=rows.slice(0,500).map(x=>({id:cleanId(x.id)||id('idea'),playerId:cleanId(x.playerId),name:x.name?cleanName(x.name):'',game:cleanIdeaGame(x.game),kind:cleanIdeaKind(x.kind),idea:cleanIdeaText(x.idea,1200),createdAt:x.createdAt||new Date().toISOString(),hidden:Boolean(x.hidden),implemented:Boolean(x.implemented)})).filter(x=>x.idea);saveCommunityIdeas();return json(res,200,{ok:true,ideas:publicIdeas(),allIdeas:communityIdeas},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/admin/reset-votes'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);communityVotes=normalizeVoteState({season:communityVotes.season,ballots:0,games:{},voters:{},history:communityVotes.history});saveCommunityVotes();return json(res,200,{ok:true,votes:publicVotes()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/admin/new-vote-season'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);const old={season:communityVotes.season,endedAt:new Date().toISOString(),ballots:communityVotes.ballots,games:communityVotes.games};const history=[old,...(communityVotes.history||[])].slice(0,24);communityVotes=normalizeVoteState({season:{number:(Number(communityVotes.season.number)||1)+1,startedAt:new Date().toISOString()},ballots:0,games:{},voters:{},history});saveCommunityVotes();return json(res,200,{ok:true,votes:publicVotes(),history},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/admin/clear-scores'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);scores.length=0;seenRuns.clear();rewriteScores();broadcast();return json(res,200,{ok:true,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/admin/delete-score'&&req.method==='POST')try{const b=await body(req);if(!hostAuthorized(b))return json(res,403,{ok:false,error:'Host authorization required'},origin);const i=scores.findIndex(r=>r.id===cleanId(b.scoreId));if(i<0)return json(res,404,{ok:false,error:'Score not found'},origin);const removed=scores.splice(i,1)[0];seenRuns.clear();for(const r of scores)if(r.runId)seenRuns.add(r.runId);rewriteScores();broadcast();return json(res,200,{ok:true,removed,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/live'&&req.method==='GET'){const c={id:id('presence'),playerId:cleanId(url.searchParams.get('playerId'))||id('anon'),name:cleanName(url.searchParams.get('name')),res,lastSeen:now(),closed:false};res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','access-control-allow-origin':origin,'x-accel-buffering':'no'});res.write(': connected\n\n');clients.set(c.id,c);sse(c,{type:'state',state:state()});broadcast();const timer=setInterval(()=>{c.lastSeen=now();sse(c,{type:'ping',at:now()})},15000);res.on('close',()=>{clearInterval(timer);c.closed=true;clients.delete(c.id);broadcast()});return}
 if(url.pathname==='/api/score'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),name=cleanName(b.name),runId=cleanId(b.runId)||id('run'),score=Math.max(0,Math.min(CONFIG.maxScore,Math.floor(Number(b.score)||0)));if(!pid)return json(res,400,{ok:false,error:'playerId required'},origin);if(seenRuns.has(runId))return json(res,200,{ok:true,duplicate:true,state:state()},origin);const r={id:id('score'),playerId:pid,name,score,game:'shooting-gallery',runId,createdAt:new Date().toISOString(),stats:b.stats&&typeof b.stats==='object'?b.stats:{}};saveScore(r);broadcast();return json(res,200,{ok:true,result:r,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/join'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),name=cleanName(b.name);if(!pid)return json(res,400,{ok:false,error:'playerId required'},origin);const q=queueJoin(pid,name);broadcast();return json(res,200,{ok:true,entry:q,position:duelQueue.findIndex(x=>x.playerId===pid)+1,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/heartbeat'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),q=duelQueue.find(x=>x.playerId===pid);if(q)q.lastSeen=now();return json(res,200,{ok:true,position:q?duelQueue.indexOf(q)+1:0,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/api/duel/leave'&&req.method==='POST')try{const b=await body(req),pid=cleanId(b.playerId),i=duelQueue.findIndex(x=>x.playerId===pid);if(i>=0)duelQueue.splice(i,1);broadcast();return json(res,200,{ok:true,state:state()},origin)}catch(e){return json(res,400,{ok:false,error:e.message},origin)}
 if(url.pathname==='/')return json(res,200,{ok:true,service:'Medley Arcade Website Live Authority',build:CONFIG.build,health:'/health'},origin);res.writeHead(404,{'content-type':'text/plain; charset=utf-8','access-control-allow-origin':origin});res.end('Not found')});
server.on('error',e=>{console.error('Authority server error:',e);process.exitCode=1});
console.log(`Medley Arcade 116 startup: opening port ${PORT}`);console.log(`Persistence directory: ${DATA}${persistentConfigured()?' (durable mount detected)':' (EPHEMERAL unless DATA_DIR/disk is configured)'}`);
server.listen(PORT,'0.0.0.0',()=>{console.log(`Medley_Arcade_Website_Live_116 Authority listening on ${PORT}`);loadScoresSafely();loadCommunitySafely();setInterval(()=>{prune();advanceRematches();broadcast()},1000)});
